variables:
  DOCKER_IMAGE_NAME: docker-texlive:latest-$CI_PIPELINE_ID
  DOCKER_TESTS_LOCATION: /tests

services:
  - docker:dind

stages:
  - test

test image:
  stage: test
  tags: ["Docker-in-Docker"]
  script:
    - docker info
    - echo "Create temporary docker image $DOCKER_IMAGE_NAME"
    - docker build --cache-from docker-texlive:latest -t $DOCKER_IMAGE_NAME .
    - echo "Run tests in $DOCKER_TESTS_LOCATION"
    - docker run -v $(pwd)/tests:$DOCKER_TESTS_LOCATION -w $DOCKER_TESTS_LOCATION $DOCKER_IMAGE_NAME $DOCKER_TESTS_LOCATION/run-tests.sh
  except:
    - master
    - tags
  artifacts:
    expire_in: 2 weeks 
    paths:
    - tests/artefacts
